apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: cac-node-example
  name: hello-world
spec:
  replicas: 5
  selector:
    matchLabels:
      app.kubernetes.io/name: cac-node-example
  template:
    metadata:
      labels:
        app.kubernetes.io/name: cac-node-example
    spec:
      containers:
      - image: gcr.io/week8demo-293819/cacdotnet:2.0
        name: cac
        ports:
        - containerPort: 80
